### PR TITLE
add username to bot output

### PR DESCRIPTION
**Pull request by shrugs**
Untested, but the query param is definitely 'username', so I don't think this could fail.

### CODE REVIEW

**Comment by Shrugs** [comment]
pls merge

**Comment by PFacheris** [comment]
TESTSSSSS

**Comment by Shrugs** [comment]
Here's your goddamn test:

```js
var bot = require('./bot');
var assert = require("assert");

describe('bot', function() {
  describe('#say', function() {
    it('should say "TDD is overrated"', function() {
       // I've put too much effort into this already
       // @TODO - test
    })
  })
})

```

**Comment by PFacheris** [comment]
lol lol lol lol, also, merge conflicts.

**Comment by Shrugs** [comment]
how is there a merge conflict. ugh, whatever

**Comment by Shrugs** [comment]
Closing because I'm tired of seeing this in my list of open pull requests.

I won't forget this.

**Comment by sagnew** [comment]
Hey Matt if you want to fix that conflict, I'll merge this right into master :)

**Comment by Shrugs** [comment]
Merge it, bitch.

**Comment by sagnew** [comment]
I don't know. @PFacheris can you do a code review? I would merge it, but your commit logs don't really follow our style guides.

**Comment by sagnew** [comment]
And I don't appreciate the use of profanity in your pull request. Profanity is great, but it has no place in this conversation.

**Comment by shrugs** [comment]
2righteous4me

**Comment by PFacheris** [comment]
I didn't see this. Would be happy to do code reviews for Mr. Condon in the future.

Regards,
Patrick

**Pull request merged**
